---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-controller-poc-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-controller-poc-access-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-controller-poc-api-access-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: k8s-controller-poc-sa
  namespace: default
roleRef:
  kind: Role
  name: k8s-controller-poc-access-role
  apiGroup: rbac.authorization.k8s.io
